name: Bot San Tin Sang Auto

on:
  workflow_dispatch:
  schedule:
    - cron: "*/10 * * * *"

jobs:
  run-bot:

    runs-on: ubuntu-latest

    steps:

      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup Node
        uses: actions/setup-node@v3
        with:
          node-version: "20"

      - name: Install packages
        run: npm install

      - name: Run bot
        run: node crawler.js
        env:
          FIREBASE_CONFIG: ${{ secrets.FIREBASE_CONFIG }}
